### ISSUE TITLE
SQL injection stop being sent after running sqlmap for about a minute

### ISSUE THREAD

**Issue by GuruOz** [BKreisel/sqlmap-websocket-proxy#1]
![sql proxy on the left sqlmap on the right  working](https://github.com/BKreisel/sqlmap-websocket-proxy/assets/46161797/a679f6e2-681b-45b4-9464-b45577d444cc)

The picture above shows me running these two commands:
1. sqlmap-websocket-proxy -u ws://ws.qreader.htb:5789/version -o 8083 -p '{"version": "%param%"}' --json (Left window)
2. sqlmap -u http://localhost:8083/?param1=1 --batch --risk 3 --level 5 -vvv (Right window)

Everything works fine for about a minute and then the sqlmap proxy stops sending the parameters from sqlmap. shown in the picture below:
![sql proxy not working](https://github.com/BKreisel/sqlmap-websocket-proxy/assets/46161797/0f2e1184-667e-45ae-843b-111f0cd12adf)

As we can see from the right window, SQLmap is still sending parameters but for some reason, the proxy does not see any parameters. Has anyone else faced this issue?

I have tried it with the script available from rayhan's blog as well. I am getting the same results there too. https://rayhan0x01.github.io/ctf/2021/04/02/blind-sqli-over-websocket-automation.html

**Comment by BKreisel** [comment]
Hey @GuruOz, thank you for the report. I was able to replicate this scenario on my machine as well. What you're seeing is Sqlmap attempting to do HTTP Header injection since you specified `--level 5`.  

You're not seeing a change in the "Proxied" payload as the GET parameter sqlmap sends remains static while they fiddle with the headers. 

From the sqlmap [usage docs](https://github.com/sqlmapproject/sqlmap/wiki/Usage):

> By default sqlmap tests all GET parameters and POST parameters. When the value of --level is >= 2 it tests also HTTP Cookie header values. When this value is >= 3 it tests also HTTP User-Agent and HTTP Referer header value for SQL injections.

Websockets only utilize HTTP headers during the initial handshake when upgrading from a regular HTTP request and aren't utilized for the individual data frames that contain the message. 

While I don't much expect the header injection to work on most websocket libraries (famous last words), I'll update the code to pass the headers from sqlmap along in the initial websocket connection and maybe find some way to display that to the user. 

FWIW you can use `--skip="user-agent,referer,cookie` to skip header injection for higher levels.

**Comment by GuruOz** [comment]
Thank you for the clear explanation. Learnt something new!

Cheers,
Guru

**Comment by BKreisel** [comment]
1.1.0 passes headers to the websocket now.
